Test Case Format
keith-meldcx/automation-demo pull request #1
Opened 2023-03-02 02:42 UTC by DebZakari

Test Case Format

2023-03-06 02:20 UTC, keith-meldcx reviewed
Hi @DebZakari, please see the comments for this review.

Also, some other observations:
1. Please use all-lowercase names for the packages to keep it inline with PEP8.

We're generally not very strict with naming, but following established conventions early on will make it simpler for everyone to contribute to the repo.

Don't hesitate to ask questions if you have any. 
Thank you!

2023-03-06 02:20 UTC, keith-meldcx commented on Pages/BasePage.py
> +    def get_title(self, title):
There's nothing wrong with this method, but it does feel strange to implement a 'get' method that also implicitly asserts the page title. 

I think it's fine to keep this for now.

2023-03-06 02:20 UTC, keith-meldcx commented on Pages/HomePage.py
> +        if self.is_visible(self.ACCOUNT_NAME):
No 'else' branch, this code will have no apparent effect if the element is not visible. This can be confusing to anyone using the method.

2023-03-06 02:20 UTC, keith-meldcx commented on Pages/HomePage_1.py
> +from selenium.webdriver.common.by import By
It is generally not advised to maintain duplicate code or code that is no longer used. 

To refer to code that was already rewritten, one can check git diff in VSCode for non-committed work or compare HEAD to a previous commit for work that is already committed.

2023-03-06 02:20 UTC, keith-meldcx commented on README.md
> +# automation-demo
Great work writing this README!

2023-03-06 02:20 UTC, keith-meldcx commented on Tests/test_HomePage_1.py
> +from Config.config import TestData
Same issue w/ HomePage.py & HomePage_1.py.

2023-03-06 02:20 UTC, keith-meldcx commented on Tests/test_base.py
> +import pytest
No reason to keep this code if there's nothing inside the BaseTest class.
I think it's possible to set "init_driver" to autouse via Pytest.

2023-03-06 02:22 UTC, keith-meldcx requested changes
erratum: please see previous review.

2023-03-07 14:13 UTC, DebZakari commented on Config/config.py
> +    HOME_PAGE_TIMESTAMP = "Last updated 02 Mar 2023, 03:46 PM"
No sir. This was also my concern about dynamic inputs from the page. It requires specific inputs pud from the user. Like the time and date in this case.

2023-03-15 09:35 UTC, keith-meldcx approved these changes
Looks good to me :+1:

2023-03-15 09:35 UTC, keith-meldcx commented on pages/login_page.py
> +    def stay(self):
Please do not create interdependent tests.

2023-03-15 09:35 UTC, merged